//
// Generated file, do not edit! Created by opp_msgtool 6.0 from txc1.msg.
//

#ifndef __TXC1_M_H
#define __TXC1_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Txc1Msg;
/**
 * Class generated from <tt>txc1.msg:3</tt> by opp_msgtool.
 * <pre>
 * message Txc1Msg
 * {
 *     int source;
 *     int destination;
 *     int hopCount = 0;
 *     int myNumber;
 * }
 * </pre>
 */
class Txc1Msg : public ::omnetpp::cMessage
{
  protected:
    int source = 0;
    int destination = 0;
    int hopCount = 0;
    int myNumber = 0;

  private:
    void copy(const Txc1Msg& other);

  protected:
    bool operator==(const Txc1Msg&) = delete;

  public:
    Txc1Msg(const char *name=nullptr, short kind=0);
    Txc1Msg(const Txc1Msg& other);
    virtual ~Txc1Msg();
    Txc1Msg& operator=(const Txc1Msg& other);
    virtual Txc1Msg *dup() const override {return new Txc1Msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSource() const;
    virtual void setSource(int source);

    virtual int getDestination() const;
    virtual void setDestination(int destination);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual int getMyNumber() const;
    virtual void setMyNumber(int myNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Txc1Msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Txc1Msg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Txc1Msg *fromAnyPtr(any_ptr ptr) { return check_and_cast<Txc1Msg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TXC1_M_H

